### ISSUE TITLE
百度网盘链接已达到访问上限

### ISSUE THREAD

**Issue by Daniel00ll** [MENGM0/UAV-SOD#1]
您好，目前百度网盘链接已达到访问上限，请问能否重新分享一个链接呢？感谢！
![image](https://github.com/MENGM0/UAV-SOD/assets/62269867/a62fad34-3edc-4a5e-8072-882b6b000e6e)

**Comment by MENGM0** [comment]
> 您好，目前百度网盘链接已达到访问上限，请问能否重新分享一个链接呢？感谢！ ![image](https://private-user-images.githubusercontent.com/62269867/337300478-a62fad34-3edc-4a5e-8072-882b6b000e6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODcwMDIsIm5iZiI6MTcxNzY4NjcwMiwicGF0aCI6Ii82MjI2OTg2Ny8zMzczMDA0NzgtYTYyZmFkMzQtM2VkYy00YTVlLTgwNzItODgyYjZiMDAwZTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE1MTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTlkZDJhNTQzMzkyNzU4YzBkM2EzOWU5MGE2YzhmOTZmMGMyOTM4YTllYzM5ZDUyMGNmOTA4MGZjMTRiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VZlXO6uJAR398Qw8zZOqBdjrd2rroaTQn1L75DXcWxY)

链接：https://pan.baidu.com/s/1d85Q5SPc-c72lqFIEjhFhg?pwd=6w4p 
提取码：6w4p

**Comment by yongchangxu** [comment]
您好，请问您可以重新提供一下百度网盘的链接吗，这个链接过期了，谢谢您

**Comment by MENGM0** [comment]
> 您好，请问您可以重新提供一下百度网盘的链接吗，这个链接过期了，谢谢您
链接: https://pan.baidu.com/s/1ycFerIu3yOjpCMQamND0KA?pwd=j8ey 提取码: j8ey

**Comment by lzzzbbbbb** [comment]
您好，请问您可以重新提供一下百度网盘的链接吗，这个链接过期了，谢谢您

**Comment by zmy587703-glitch** [comment]
您好，链接过期了，请问您可以重新分享一下百度网盘的链接吗？大学生做毕设需要用到，十分谢谢

**Comment by MENGM0** [comment]
通过网盘分享的文件：uav_imagry_sewage_outfall_dataset.zip
链接: https://pan.baidu.com/s/1iWy33obezsKPYteHbhpVzw?pwd=pt5e 提取码: pt5e




黄庆松
***@***.***
